apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: bison.mysaxion.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bison-svc
            port:
              number: 80
  - host: brightspace.mysaxion.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brightspace-svc
            port:
              number: 80
